version: '2'
services:
    codeblog-app:
        image: codeblog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://codeblog-mysql:3306/codeblog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    codeblog-mysql:
        extends:
            file: mysql.yml
            service: codeblog-mysql
